version: "3.9"

services:
  app:
    build: .
    container_name: secretsanta_app
    ports:
      - "8080:80"
    environment:
      APP_BASE_URL: "http://localhost:8080"

      DB_HOST: "db"
      DB_PORT: "3306"
      DB_NAME: "secret_santa"
      DB_USER: "secretsanta"
      DB_PASSWORD: "changeme"

      # Timezone
      APP_TZ: "America/New_York"
      TZ: "America/New_York"

      # For dev: send mail to MailHog instead of real SMTP
      SMTP_HOST: "mailhog"
      SMTP_PORT: "1025"
      SMTP_USER: ""
      SMTP_PASS: ""
      SMTP_FROM_EMAIL: "santa@example.test"
      SMTP_FROM_NAME: "Secret Santa Bot"
    depends_on:
      - db
      - mailhog
    volumes:
      - ./src:/var/www/html

  db:
    image: mariadb:11
    container_name: secretsanta_db
    restart: unless-stopped
    environment:
      TZ: "America/New_York"
      MYSQL_ROOT_PASSWORD: "changeme"
      MYSQL_DATABASE: "secret_santa"
      MYSQL_USER: "secretsanta"
      MYSQL_PASSWORD: "changeme"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro

  mailhog:
    image: mailhog/mailhog
    container_name: secretsanta_mailhog
    restart: unless-stopped
    environment:
      TZ: "America/New_York"
    ports:
      - "8025:8025"  # Web UI: http://localhost:8025
    # SMTP is on port 1025 inside the Docker network

volumes:
  db_data:

